from random import shuffle
from PyQt5 import QtCore, QtGui, QtWidgets

class JeuDeCartes(object):

    def __init__(self):
        """Construction du jeu de carte"""
        self.carte = []  # Liste vide à remplir
        """Simulation d'un jeu de 52 cartes"""
        # Valeur des cartes
        self.valeur = [2, 3, 4, 5, 6, 7, 8, 9, 10, "valet", "dame", "roi", "as"]
        # Couleur de la carte
        self.couleur = ["Trèfle", "Carreau", "Coeur", "Pique"]
        for indiceCouleur in range(len(self.couleur)):
            for indiceValeur in range(len(self.valeur)):
                self.carte.append((indiceValeur, indiceCouleur))
                
        self.images = {(0, 0): "01",(1, 0): "02",(2, 0): "03",(3, 0): "04",(4, 0): "05",(5, 0): "06",(6, 0): "07",(7, 0): "08",(8, 0): "09",(9, 0): "10",(10, 0): "11",(11, 0): "12",(12, 0): "00",
                       (0, 1): "14",(1, 1): "15",(2, 1): "16",(3, 1): "17",(4, 1): "18",(5, 1): "19",(6, 1): "20",(7, 1): "21",(8, 1): "22",(9, 1): "23",(10, 1): "24",(11, 1): "25",(12, 1): "13",
                       (0, 2): "27",(1, 2): "28",(2, 2): "29",(3, 2): "30",(4, 2): "31",(5, 2): "32",(6, 2): "33",(7, 2): "34",(8, 2): "35",(9, 2): "36",(10, 2): "37",(11, 2): "38",(12, 2): "26",
                       (0, 3): "40",(1, 3): "41",(2, 3): "42",(3, 3): "43",(5, 3): "44",(4, 3): "45",(6, 3): "46",(7, 3): "47",(8, 3): "48",(9, 3): "49",(10, 3): "50",(11, 3): "51",(12, 3): "39"}

    def nomCarte(self, c):
        """Renvoie le nom de la carte (<c> doit être un tuple !!!)"""
        if self.carte != []:
            return str(self.valeur[c[0]])+" de "+str(self.couleur[c[1]])

    def battre(self):
        """Mélange les cartes"""
        shuffle(self.carte)

    def tirer(self):
        """Retire une carte du jeu"""
        if self.carte != []:
            self.carteTirer = self.carte[0]
            del(self.carte[0])
            #print(f"{self.valeur[self.carteTirer[0]]} de {self.couleur[self.carteTirer[1]]}")
            
        else:
            print("Plus de cartes")
            
        
        return self.carteTirer


class Ui_MainWindow_StartMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 451, 161))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 130, 201, 51))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 210, 201, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(120, 20, 71, 51))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 71, 51))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 240, 151, 31))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Jeu De Carte"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.groupBox.setTitle(_translate("MainWindow", "PlayerSelection"))
        self.radioButton_2.setText(_translate("MainWindow", "Joueur 2"))
        self.radioButton.setText(_translate("MainWindow", "Joueur 1"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "IP du second Joueur"))


class Ui_MainWindow_Player1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.player1 = QtWidgets.QGroupBox(self.centralwidget)
        self.player1.setGeometry(QtCore.QRect(0, 280, 451, 291))
        self.player1.setAutoFillBackground(True)
        self.player1.setFlat(False)
        self.player1.setObjectName("player1")
        self.IP_SENDER_LABEL = QtWidgets.QLabel(self.player1)
        self.IP_SENDER_LABEL.setGeometry(QtCore.QRect(30, 160, 151, 41))
        self.IP_SENDER_LABEL.setObjectName("IP_SENDER_LABEL")
        self.cartePlacerA = QtWidgets.QLabel(self.player1)
        self.cartePlacerA.setGeometry(QtCore.QRect(30, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cartePlacerA.setFont(font)
        self.cartePlacerA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cartePlacerA.setWordWrap(True)
        self.cartePlacerA.setObjectName("cartePlacerA")
        self.scoreA = QtWidgets.QLabel(self.player1)
        self.scoreA.setGeometry(QtCore.QRect(30, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scoreA.setFont(font)
        self.scoreA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreA.setWordWrap(True)
        self.scoreA.setObjectName("scoreA")
        self.carteChoisieA = QtWidgets.QLabel(self.player1)
        self.carteChoisieA.setGeometry(QtCore.QRect(280, 50, 161, 221))
        self.carteChoisieA.setText("")
        self.carteChoisieA.setPixmap(QtGui.QPixmap("Resources/data/54.png"))
        self.carteChoisieA.setScaledContents(True)
        self.carteChoisieA.setAlignment(QtCore.Qt.AlignCenter)
        self.carteChoisieA.setWordWrap(False)
        self.carteChoisieA.setIndent(1)
        self.carteChoisieA.setObjectName("carteChoisieA")
        self.currentCardA = QtWidgets.QLabel(self.player1)
        self.currentCardA.setGeometry(QtCore.QRect(30, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currentCardA.setFont(font)
        self.currentCardA.setText("")
        self.currentCardA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.currentCardA.setWordWrap(True)
        self.currentCardA.setObjectName("currentCardA")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 0, 451, 291))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.scoreB = QtWidgets.QLabel(self.groupBox)
        self.scoreB.setGeometry(QtCore.QRect(250, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scoreB.setFont(font)
        self.scoreB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreB.setWordWrap(True)
        self.scoreB.setObjectName("scoreB")
        self.IP_RECEVEUR_LABEL = QtWidgets.QLabel(self.groupBox)
        self.IP_RECEVEUR_LABEL.setGeometry(QtCore.QRect(250, 140, 151, 41))
        self.IP_RECEVEUR_LABEL.setObjectName("IP_RECEVEUR_LABEL")
        self.currentCardB = QtWidgets.QLabel(self.groupBox)
        self.currentCardB.setGeometry(QtCore.QRect(250, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currentCardB.setFont(font)
        self.currentCardB.setText("")
        self.currentCardB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.currentCardB.setWordWrap(True)
        self.currentCardB.setObjectName("currentCardB")
        self.cartePlacerB = QtWidgets.QLabel(self.groupBox)
        self.cartePlacerB.setGeometry(QtCore.QRect(250, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cartePlacerB.setFont(font)
        self.cartePlacerB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cartePlacerB.setWordWrap(True)
        self.cartePlacerB.setObjectName("cartePlacerB")
        self.carteChoisieB = QtWidgets.QLabel(self.groupBox)
        self.carteChoisieB.setGeometry(QtCore.QRect(30, 30, 161, 221))
        self.carteChoisieB.setText("")
        self.carteChoisieB.setPixmap(QtGui.QPixmap("Resources/data/54.png"))
        self.carteChoisieB.setScaledContents(True)
        self.carteChoisieB.setAlignment(QtCore.Qt.AlignCenter)
        self.carteChoisieB.setWordWrap(False)
        self.carteChoisieB.setIndent(1)
        self.carteChoisieB.setObjectName("carteChoisieB")
        self.currentWinner = QtWidgets.QLabel(self.centralwidget)
        self.currentWinner.setGeometry(QtCore.QRect(190, 270, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentWinner.setFont(font)
        self.currentWinner.setAutoFillBackground(True)
        self.currentWinner.setObjectName("currentWinner")
        self.sendingButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendingButton.setGeometry(QtCore.QRect(460, 310, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.sendingButton.setFont(font)
        self.sendingButton.setObjectName("sendingButton")
        self.labelReady = QtWidgets.QLabel(self.centralwidget)
        self.labelReady.setGeometry(QtCore.QRect(30, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.labelReady.setFont(font)
        self.labelReady.setObjectName("labelReady")
        self.showPossibleCards = QtWidgets.QPushButton(self.centralwidget)
        self.showPossibleCards.setGeometry(QtCore.QRect(480, 370, 171, 41))
        self.showPossibleCards.setObjectName("showPossibleCards")
        self.addCard = QtWidgets.QPushButton(self.centralwidget)
        self.addCard.setGeometry(QtCore.QRect(480, 420, 171, 41))
        self.addCard.setObjectName("addCard")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.player1.setTitle(_translate("MainWindow", "Joueur 1"))
        self.IP_SENDER_LABEL.setText(_translate("MainWindow", "Votre IP :"))
        self.cartePlacerA.setText(_translate("MainWindow", "Carte Placée:  currentCardA"))
        self.scoreA.setText(_translate("MainWindow", "Score : "))
        self.groupBox.setTitle(_translate("MainWindow", "Joueur 2"))
        self.scoreB.setText(_translate("MainWindow", "Score : "))
        self.IP_RECEVEUR_LABEL.setText(_translate("MainWindow", "Leur IP :"))
        self.cartePlacerB.setText(_translate("MainWindow", "Carte Placée:  currentCardA"))
        self.currentWinner.setText(_translate("MainWindow", "Round N | WINNER : PLACEHOLDER"))
        self.sendingButton.setText(_translate("MainWindow", "Envoyer la carte choisie"))
        self.labelReady.setText(_translate("MainWindow", "Joueur 2 :"))
        self.showPossibleCards.setText(_translate("MainWindow", "Afficher Mes Cartes"))
        self.addCard.setText(_translate("MainWindow", "Add a Card"))

class Ui_MainWindow_Player2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showPossibleCards = QtWidgets.QPushButton(self.centralwidget)
        self.showPossibleCards.setGeometry(QtCore.QRect(30, 100, 171, 41))
        self.showPossibleCards.setObjectName("showPossibleCards")
        self.addCard = QtWidgets.QPushButton(self.centralwidget)
        self.addCard.setGeometry(QtCore.QRect(30, 150, 171, 41))
        self.addCard.setObjectName("addCard")
        self.sendingButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendingButton.setGeometry(QtCore.QRect(10, 40, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.sendingButton.setFont(font)
        self.sendingButton.setObjectName("sendingButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 10, 451, 291))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.scoreB = QtWidgets.QLabel(self.groupBox)
        self.scoreB.setGeometry(QtCore.QRect(250, 70, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scoreB.setFont(font)
        self.scoreB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreB.setWordWrap(True)
        self.scoreB.setObjectName("scoreB")
        self.IP_RECEVEUR_LABEL = QtWidgets.QLabel(self.groupBox)
        self.IP_RECEVEUR_LABEL.setGeometry(QtCore.QRect(250, 140, 151, 41))
        self.IP_RECEVEUR_LABEL.setObjectName("IP_RECEVEUR_LABEL")
        self.currentCardB = QtWidgets.QLabel(self.groupBox)
        self.currentCardB.setGeometry(QtCore.QRect(250, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currentCardB.setFont(font)
        self.currentCardB.setText("")
        self.currentCardB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.currentCardB.setWordWrap(True)
        self.currentCardB.setObjectName("currentCardB")
        self.cartePlacerB = QtWidgets.QLabel(self.groupBox)
        self.cartePlacerB.setGeometry(QtCore.QRect(250, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cartePlacerB.setFont(font)
        self.cartePlacerB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cartePlacerB.setWordWrap(True)
        self.cartePlacerB.setObjectName("cartePlacerB")
        self.carteChoisieB = QtWidgets.QLabel(self.groupBox)
        self.carteChoisieB.setGeometry(QtCore.QRect(30, 30, 161, 221))
        self.carteChoisieB.setText("")
        self.carteChoisieB.setPixmap(QtGui.QPixmap("Resources/data/54.png"))
        self.carteChoisieB.setScaledContents(True)
        self.carteChoisieB.setAlignment(QtCore.Qt.AlignCenter)
        self.carteChoisieB.setWordWrap(False)
        self.carteChoisieB.setIndent(1)
        self.carteChoisieB.setObjectName("carteChoisieB")
        self.player1 = QtWidgets.QGroupBox(self.centralwidget)
        self.player1.setGeometry(QtCore.QRect(0, 290, 451, 291))
        self.player1.setAutoFillBackground(True)
        self.player1.setFlat(False)
        self.player1.setObjectName("player1")
        self.IP_SENDER_LABEL = QtWidgets.QLabel(self.player1)
        self.IP_SENDER_LABEL.setGeometry(QtCore.QRect(30, 160, 151, 41))
        self.IP_SENDER_LABEL.setObjectName("IP_SENDER_LABEL")
        self.cartePlacerA = QtWidgets.QLabel(self.player1)
        self.cartePlacerA.setGeometry(QtCore.QRect(30, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cartePlacerA.setFont(font)
        self.cartePlacerA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.cartePlacerA.setWordWrap(True)
        self.cartePlacerA.setObjectName("cartePlacerA")
        self.scoreA_5 = QtWidgets.QLabel(self.player1)
        self.scoreA_5.setGeometry(QtCore.QRect(30, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.scoreA_5.setFont(font)
        self.scoreA_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scoreA_5.setWordWrap(True)
        self.scoreA_5.setObjectName("scoreA_5")
        self.carteChoisieA = QtWidgets.QLabel(self.player1)
        self.carteChoisieA.setGeometry(QtCore.QRect(280, 50, 161, 221))
        self.carteChoisieA.setText("")
        self.carteChoisieA.setPixmap(QtGui.QPixmap("Resources/data/54.png"))
        self.carteChoisieA.setScaledContents(True)
        self.carteChoisieA.setAlignment(QtCore.Qt.AlignCenter)
        self.carteChoisieA.setWordWrap(False)
        self.carteChoisieA.setIndent(1)
        self.carteChoisieA.setObjectName("carteChoisieA")
        self.currentCardA = QtWidgets.QLabel(self.player1)
        self.currentCardA.setGeometry(QtCore.QRect(30, 140, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currentCardA.setFont(font)
        self.currentCardA.setText("")
        self.currentCardA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.currentCardA.setWordWrap(True)
        self.currentCardA.setObjectName("currentCardA")
        self.labelReady = QtWidgets.QLabel(self.centralwidget)
        self.labelReady.setGeometry(QtCore.QRect(520, 440, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.labelReady.setFont(font)
        self.labelReady.setObjectName("labelReady")
        self.currentWinner = QtWidgets.QLabel(self.centralwidget)
        self.currentWinner.setGeometry(QtCore.QRect(180, 270, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentWinner.setFont(font)
        self.currentWinner.setAutoFillBackground(True)
        self.currentWinner.setObjectName("currentWinner")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showPossibleCards.setText(_translate("MainWindow", "Afficher Mes Cartes"))
        self.addCard.setText(_translate("MainWindow", "Add a Card"))
        self.sendingButton.setText(_translate("MainWindow", "Envoyer la carte choisie"))
        self.groupBox.setTitle(_translate("MainWindow", "Joueur 2"))
        self.scoreB.setText(_translate("MainWindow", "Score : "))
        self.IP_RECEVEUR_LABEL.setText(_translate("MainWindow", "Votre IP :"))
        self.cartePlacerB.setText(_translate("MainWindow", "Carte Placée:  currentCardA"))
        self.player1.setTitle(_translate("MainWindow", "Joueur 1"))
        self.IP_SENDER_LABEL.setText(_translate("MainWindow", "Leur IP :"))
        self.cartePlacerA.setText(_translate("MainWindow", "Carte Placée:  currentCardA"))
        self.scoreA_5.setText(_translate("MainWindow", "Score : "))
        self.labelReady.setText(_translate("MainWindow", "Joueur 1 :"))
        self.currentWinner.setText(_translate("MainWindow", "Round N | WINNER : PLACEHOLDER"))